### ISSUE TITLE
data_interface examples do not work

### ISSUE THREAD

**Issue by flurischt** [lobbywatch/lobbywatch#7]
I just tried out a couple of the examples mentioned here:
https://github.com/lobbywatch/lobbywatch/blob/master/drupal/lobbywatch/lobbywatch_data/data_interface_description.md

E.g. Example 1 `call http://lobbywatch.ch/de/data/interface/v1/json/table/branche/flat/id/1` yields a 404 Error.

**Comment by scito** [comment]
Fixed links to dataIF after migration.
Thanks for reporting.

**Comment by flurischt** [comment]
awesome thanks! Btw: Also some links here need fixes: https://lobbywatch.ch/de/seite/technik

E.g "Vereinfachtes Datenmodell".

**Comment by scito** [comment]
Links fixed.

Actually, due to migration problems with DNS, other migration parts such as updating/checking links could not be done yet.

I'm happy to hear if you find other problems.
